### ISSUE TITLE
Choosing input files for the tracker

### ISSUE THREAD

**Issue by redcatbear** [hamstercommunity/openfasttrack#5]
As a quality engineer
I want to run OFT on a list of files / and or directories (including their sub-directories)
in order to check requirement coverage over a whole project.
## Acceptance criteria
1. OFT accepts a list of input files as parameter
2. OFT accepts a list of input directories as parameter
3. OFT scans a files given directly and which are below a given input directory
4. OFT scans each file only once

**Comment by kaklakariada** [comment]
@redcatbear This is implemented and can be closed (no pull request, review in #11).
