### ISSUE TITLE
Newline escape char on windows fails unit tests on windows 

### ISSUE THREAD

**Issue by quarterbit** [hamstercommunity/openfasttrack#58]
Test testTraceWithReportVerbosityMinimal fails because it expects fileContent(this.outputFile), equalTo("not ok\n") but get on windows for fileContent(this.outputFile) _"not ok\r\n"_

**Comment by quarterbit** [comment]
Finding: Converted LineEnding in Eclipse of the \src\test\resources\specobject files to Unix style which helped to get all Junit Cases to run successfull

**Comment by redcatbear** [comment]
# Design Considerations
On import we want to be flexible: we accept *nix-style, windows-style and even the old mac-style line endings - also mixed in one file.

For output we use the platform standard unless configured otherwise explicitly by the user.

**Comment by redcatbear** [comment]
@quarterbit: Changes merged, please retest.
